before_script:
  - ls /usr/local/bin
  - echo $PATH
  - curl -sSL https://get.docker.com/ | sh
  - sudo usermod -aG docker your-user
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD

build_image:
  script:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker stop gameroom_server
    - docker rm -f coreykruger/gameroom:latest
    - docker build -f Dockerfile -t coreykruger/gameroom .

push_image:
  script:
    - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push coreykruger/gameroom