before_script:
  - sudo docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD

build_image:
  script:
    - sudo docker stop gameroom_server
    - sudo docker rm -f coreykruger/gameroom:latest
    - sudo docker build -f Dockerfile -t coreykruger/gameroom .

push_image:
  script:
    - sudo docker push coreykruger/gameroom