before_script:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build -t coreykruger/gameroom .

build_image:
  script:
    - docker stop gameroom_server
    - docker rm -f coreykruger/gameroom:latest
    - docker build -f Dockerfile -t gameroom .

push_image:
  script:
    - docker push coreykruger/gameroom